# Generated by Django 4.0 on 2022-06-01 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0004_refer_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Refer_MOdel',
            new_name='Refer',
        ),
    ]
