# Generated by Django 4.0 on 2022-06-10 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_refer_model_refer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refer',
            name='autoPlacement',
        ),
    ]
