# Generated by Django 4.0 on 2022-06-22 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('affilate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.CharField(max_length=200, unique=True)),
                ('amount', models.FloatField(default=0)),
                ('USDT', models.FloatField(default=0)),
                ('TRX', models.FloatField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
