# Generated by Django 4.0 on 2022-06-22 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affilate', '0002_user_bonus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_bonus',
        ),
    ]
