# Generated by Django 4.0 on 2022-06-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affilate', '0004_user_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_bonus',
            name='bonus',
            field=models.CharField(max_length=200),
        ),
    ]
