# Generated by Django 4.0 on 2022-06-25 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('affilate', '0006_user_transcations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_transcations',
            name='credited',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='user_seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=200)),
                ('seed_value', models.IntegerField(default=0)),
                ('paid', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
